title = "Grimoh's Blog"
baseurl = "https://blog.grimoh.net/"
theme = "hugo-ink"
languageCode = "eu-us"
hasCJKLanguage = true
paginate = 5
copyright = "Â© Copyright 2020 grimoh"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-137907582-1"
disqusShortname = ""

[params]
	subtitle = "I'm a SRE as well as a Vampire. ğŸ¦‡ â˜”ï¸ ğŸ¦„ ğŸ°"
	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
	featherIconsCDN = true
	mode = "auto" # "dark" or "auto"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/grimoh"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/grim0h"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
	tag = "tags"
	category = "categories"
